project:
  name: "Vetheris"
  version: "1.0.0"

arqos:
  mode: fullstack

  components:
    - harbor: ^1.3.0
    - dnabase: ^2.2.0
    - strategos: ^2.3.0
    - pipeline: ^2.2.0

  custom_agents:
    - Narrator
    - CombatManager
    - CharacterEvolver

  ae2_config:
    domain: gaming
    orchestration: internal_flow
    strategic_objectives:
      - narrative_immersion
      - structural_coherence
      - system_transparency

  ae3_config:
    enabled_tools:
      - UserIntentParser
      - ChainOfThoughtGenerator
      - PVASNarrator
      - HybridNarrator
      - ToneAgent
